#!/bin/bash

export SCENETEST_PATH=`pwd`

git pull
go get -u
go build

./scenetest setup -info Regression.json \
    -platform-url "http://127.0.0.1:9000" \
    -messaging-url "127.0.0.1:1883" \
    setup/novi.json

if [ $? -eq 0 ]; then
    echo "SETUP SUCCESS"
else
    echo "SETUP FAILURE"
    exit 1
fi

while read TestFileName; do
    echo "****************************** $TestFileName ******************************"
    ./scenetest run -overrides=JenkinsOverrides.json -info Regression.json $TestFileName
    if [ $? -eq 0 ]; then
        echo "SUCCESS"
    else
        echo "FAIL"
        exit 1
    fi
done < BuildTests

./scenetest teardown -info Regression.json

if [ $? -eq 0 ]; then
    echo "TEARDOWN SUCCESS"
else
    echo "TEARDOWN FAILURE"
    exit 1
fi

rm -f Regression.json

exit 0
